import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {describe,it} from "node:test";

const root=path.resolve(process.cwd(),"..","..");

function readProjectFile(relativePath){
  return fs.readFileSync(path.join(root,relativePath),"utf8");
}

describe("admin v2 dashboard and customer overview",()=>{
  it("loads real admin customers through the existing Firebase database facade",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/withTimeout\(window\.ACTFirebaseAuth\.requireAdmin\(\),AUTH_TIMEOUT_MS,"requireAdmin"\)/);
    assert.match(js,/withTimeout\(window\.ACTFirebaseDatabase\.loadCustomersForAdmin\(\),AUTH_TIMEOUT_MS,"loadCustomersForAdmin"\)/);
    assert.doesNotMatch(js,/Familie Mueller|Familie Rossi|Herr Schneider|mockCustomers|Mock-Daten/i);
  });

  it("guards admin v2 authentication against permanent loading states",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    const html=readProjectFile("customer-portal/admin-v2.html");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(js,/const AUTH_TIMEOUT_MS=15000/);
    assert.match(js,/function withTimeout\(promise,timeoutMs,label\)/);
    assert.match(js,/function startLoginDeadline\(attemptId\)/);
    assert.match(js,/activeLoginAttempt!==attemptId/);
    assert.match(js,/UI-Deadline erreicht/);
    assert.match(js,/setLoginLoading\(true,"Anmeldung wird gepr/);
    assert.match(js,/button\.disabled=Boolean\(isLoading\)/);
    assert.match(js,/const TECHNICAL_LOGIN_ERROR="Die Anmeldung konnte nicht abgeschlossen werden\. Bitte erneut versuchen\."/);
    assert.match(js,/const MISSING_ROLE_ERROR="Dieses Konto besitzt keine Berechtigung f/);
    assert.match(js,/console\.error\("\[ACT Admin V2\] Anmeldung:"/);
    assert.match(html,/firebase-auth\.js\?v=3/);
    assert.match(html,/admin-v2\.css\?v=26/);
    assert.match(html,/admin-v2\.js\?v=26/);
    assert.match(css,/\[hidden\]\{display:none!important\}/);
    assert.doesNotMatch(html,/data-icon=/);
    assert.match(html,/class="v2-nav-icon"/);
  });

  it("keeps dashboard as cockpit and customer cards in the customer view only",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    const html=readProjectFile("customer-portal/admin-v2.html");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(html,/id="todayList"/);
    assert.match(html,/id="activityList"/);
    assert.doesNotMatch(html,/Schnellzugriffe|v2-quick-grid|dashboardQuickNewCustomerButton|dashboardNewCustomerButton|id="newCustomerButton"/);
    assert.match(html,/id="customerNewButton">Neuer Kunde/);
    assert.equal((html.match(/Neuer Kunde/g)||[]).length,1);
    assert.match(js,/icon:"users"/);
    assert.match(js,/class="v2-card-icon \$\{escapeHtml\(item\.icon\)\}"/);
    assert.match(css,/\.v2-metric-copy\{position:relative;z-index:1;display:grid/);
    assert.match(css,/\.v2-card-icon\.check::after/);
    assert.match(html,/id="customerGrid"/);
    assert.match(js,/Heute Anreisen/);
    assert.match(js,/Heute Abreisen/);
    assert.match(js,/function todayItem\(customer\)/);
    assert.match(js,/function activityItem\(customer\)/);
    assert.match(css,/\.v2-dashboard-grid/);
    assert.match(css,/\.v2-customer-card:hover/);
    assert.match(js,/class="v2-card v2-customer-card" tabindex="0" role="button" data-open-editor/);
  });

  it("keeps login and dashboard mutually exclusive after auth state changes",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/function setScreenVisibility\(loginVisible\)/);
    assert.match(js,/login\.hidden=!loginVisible/);
    assert.match(js,/shell\.hidden=loginVisible/);
    assert.match(js,/function showShell\(authState\)\{\s*setLoginLoading\(false\);\s*clearPassword\(\);\s*setScreenVisibility\(false\);/);
    assert.match(js,/function resetHorizontalScroll\(\)/);
    assert.match(js,/document\.documentElement\.scrollLeft=0/);
    assert.match(js,/window\.scrollTo\(\{top:0,left:0,behavior:"auto"\}\)/);
  });

  it("bounds Firebase auth and claim operations used by admin login",()=>{
    const authJs=readProjectFile("customer-portal/firebase-auth.js");
    assert.match(authJs,/const AUTH_OPERATION_TIMEOUT_MS=15000/);
    assert.match(authJs,/function withTimeout\(promise,ms,label\)/);
    assert.match(authJs,/firebaseService\.init\(\{anonymous:false\}\),AUTH_OPERATION_TIMEOUT_MS,"Firebase init"/);
    assert.match(authJs,/currentUser\.getIdTokenResult\(Boolean\(forceRefresh\)\),AUTH_OPERATION_TIMEOUT_MS,"Firebase claims"/);
    assert.match(authJs,/signInWithEmailAndPassword\(context\.auth,email,password\)/);
    assert.match(authJs,/AUTH_OPERATION_TIMEOUT_MS,\s*"Firebase signIn"/);
    assert.match(authJs,/context\.authModule\.signOut\(context\.auth\),AUTH_OPERATION_TIMEOUT_MS,"Firebase signOut"/);
    assert.match(authJs,/auth\/operation-timeout/);
  });

  it("opens customer cards in a read-only v2 detail route",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    const html=readProjectFile("customer-portal/admin-v2.html");
    assert.match(html,/id="customerDetailView"/);
    assert.match(html,/id="customerDetailRoot"/);
    assert.match(js,/function parseRoute\(hashValue\)/);
    assert.match(js,/route:"customerDetail"/);
    assert.match(js,/function detailHash\(id,tab="kunde"\)/);
    assert.match(js,/function openCustomerDetail\(id\)/);
    assert.match(js,/routeTo\(`customers\/\$\{encodeURIComponent\(id\)\}\/kunde`\)/);
    assert.match(js,/data-open-editor="\$\{escapeHtml\(customer\.customerId\)\}"/);
    assert.match(js,/window\.addEventListener\("popstate",\(\)=>\{/);
    assert.match(js,/if\(!routeTo\(location\.hash\|\|"#dashboard",\{replace:true\}\)\)history\.pushState\(\{route:state\.route\},"",currentRouteHash\(\)\)/);
  });

  it("renders customer tab from loaded customer data without mock data or inputs",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/function renderCustomerDetail\(\)/);
    assert.match(js,/const customer=customerById\(state\.selectedCustomerId\)/);
    assert.match(js,/function customerTabMarkup\(customer\)/);
    assert.match(js,/Kundenname/);
    assert.match(js,/Begleitpersonen/);
    assert.match(js,/Telefonnummer/);
    assert.match(js,/Anforderungen \/ Wuensche/);
    assert.match(js,/role="tablist"/);
    assert.match(js,/aria-selected="\$\{key===tab\?"true":"false"\}"/);
    assert.match(js,/tab==="programm"\?programTabMarkup\(customer\):tab==="dokumente"\?documentsTabMarkup\(customer\):tab==="veroeffentlichung"\?publicationTabMarkup\(customer\):placeholderTabMarkup\(\)/);
    assert.doesNotMatch(js,/Familie Mueller|Familie Rossi|Herr Schneider|mockCustomers|Mock-Daten/i);
    assert.match(js,/data-customer-edit-action="edit">Bearbeiten/);
  });

  it("renders the trip tab read-only from the already loaded customer object",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(js,/tab==="reise"\?tripTabMarkup\(customer\):tab==="programm"\?programTabMarkup\(customer\):tab==="dokumente"\?documentsTabMarkup\(customer\):tab==="veroeffentlichung"\?publicationTabMarkup\(customer\):placeholderTabMarkup\(\)/);
    assert.match(js,/function buildTripViewModel\(customer\)/);
    assert.match(js,/function tripTabMarkup\(customer\)/);
    assert.match(js,/const travel=objectValue\(customer\.travel,customer\.trip,customer\.tripData,customer\.travelData,customer\.journey,customer\.reise,customer\.profile\?\.travel\)/);
    assert.match(js,/const start=firstValue\(customer\.startDatePlain,customer\.dateFrom,customer\.arrival,customer\.arrivalDate/);
    assert.match(js,/const adults=numericValue\(customer\.adults,customer\.guests\?\.adults,travel\.adults,travel\.guests\?\.adults,profile\.travel\?\.adults\)/);
    assert.match(js,/normalizeChildAgesFromSources\(\s*children,/);
    assert.match(js,/travelerSummary\(adults,children,childAges\)/);
    assert.match(js,/tripReadCard\("Reisedaten"/);
    assert.match(js,/tripReadCard\("Reisende"/);
    assert.match(js,/tripReadCard\("An- und Abreise"/);
    assert.match(js,/tripReadCard\("Region und Aufenthalt"/);
    assert.match(js,/tripReadCard\("Wuensche und Hinweise"/);
    assert.match(js,/Fuer diesen Kunden sind noch keine Reisedaten hinterlegt\./);
    assert.match(js,/Im klassischen Admin bearbeiten/);
    assert.match(js,/data-trip-edit-action="edit">Reise bearbeiten/);
    assert.match(css,/\.v2-trip-hero/);
    assert.match(css,/\.v2-trip-grid/);
    assert.match(css,/\.v2-internal-field span::after\{content:" intern"/);
  });

  it("supports controlled trip edit mode with validation, cancel and dirty warning",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/tripEditMode:false/);
    assert.match(js,/tripEditDraft:null/);
    assert.match(js,/function tripEditValues\(customer\)/);
    assert.match(js,/function startTripEdit\(customer\)/);
    assert.match(js,/function cancelTripEdit\(\)/);
    assert.match(js,/function hasDirtyTripEdit\(\)/);
    assert.match(js,/function hasDirtyEdits\(\)/);
    assert.match(js,/function tripChildAgeFields\(draft,errors=\{\}\)/);
    assert.match(js,/Alter Kind \$\{index\+1\}/);
    assert.match(js,/id="tripTravelerPreview"/);
    assert.match(js,/id="tripEditForm"/);
    assert.match(js,/data-trip-edit-action="save"/);
    assert.match(js,/data-trip-edit-action="cancel"/);
    assert.match(js,/tripInputField\("startDate","Von",draft\.startDate,\{type:"date"/);
    assert.match(js,/tripInputField\("endDate","Bis",draft\.endDate,\{type:"date"/);
    assert.match(js,/errors\.tripName="Bitte einen Reisenamen eingeben\."/);
    assert.match(js,/Das Bis-Datum darf nicht vor dem Von-Datum liegen\./);
    assert.match(js,/Bitte gib das Alter fuer Kind \$\{index\+1\} ein\./);
    assert.match(js,/Bitte eine ganze Zahl zwischen 0 und 17 eingeben\./);
    assert.match(js,/Bitte ein Alter zwischen 0 und 17 eingeben\./);
    assert.match(js,/Ungespeicherte Aenderungen verwerfen\?/);
    assert.match(js,/if\(!hasDirtyEdits\(\)\)return/);
  });

  it("normalizes child ages and computes traveler summary without duplicates",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/function normalizeChildAgesFromSources\(childrenCount,\.\.\.sources\)/);
    assert.match(js,/for\(const source of sources\)\{/);
    assert.match(js,/return count===null\?ages:ages\.slice\(0,count\)/);
    assert.match(js,/customer\.childAges,\s*customer\.childrenAges,\s*customer\.guests\?\.childAges/);
    assert.match(js,/travel\.childAges,\s*travel\.childrenAges,\s*travel\.kidsAges,\s*travel\.agesOfChildren/);
    assert.match(js,/customer\.kidsAges,\s*customer\.agesOfChildren,\s*customer\.childrenAge,\s*customer\.childAge/);
    assert.match(js,/function childAgeLabels\(ages\)/);
    assert.match(js,/Kind \$\{index\+1\} · \$\{age\} Jahre/);
    assert.match(js,/function travelerSummary\(adultsValue,childrenValue,agesValue=\[\]\)/);
    assert.match(js,/parts\.push\(`\$\{adults\} Erwachsene\$\{adults===1\?"r":""\}`\)/);
    assert.match(js,/parts\.push\(`\$\{children\} Kind\$\{children===1\?"":"er"\}\$\{suffix\}`\)/);
    assert.match(js,/return parts\.length\?parts\.join\(" • "\):"Keine Reisenden"/);
  });

  it("saves trip edits through the existing draft facade without replacing other flows",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/function mergeTripEdit\(customer,values\)/);
    assert.match(js,/const next=clone\(customer\)/);
    assert.match(js,/const fullCustomer=mergeTripEdit\(customer,validation\.values\)/);
    assert.match(js,/window\.ACTFirebaseDatabase\.saveDraftCustomer\(fullCustomer\)/);
    assert.match(js,/updateLocalCustomer\(fullCustomer\)/);
    assert.match(js,/Reise erfolgreich gespeichert\./);
    assert.match(js,/next\.startDatePlain=values\.startDate/);
    assert.match(js,/next\.endDatePlain=values\.endDate/);
    assert.match(js,/next\.accommodationName=values\.accommodationName/);
    assert.match(js,/target\.arrivalType=values\.arrivalType/);
    assert.match(js,/values\.childAges=values\.childAges\.slice\(0,childCount\)/);
    assert.match(js,/next\.childAges=values\.childAges/);
    assert.match(js,/next\.childrenAges=values\.childAges/);
    assert.doesNotMatch(js,/setDoc\(|updateDoc\(|deleteDoc\(|firestoreModule/);
  });

  it("activates the program tab with editable itinerary days and items",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(js,/programEditMode:false/);
    assert.match(js,/programEditDraft:null/);
    assert.match(js,/let programSavePromise=null/);
    assert.match(js,/const PROGRAM_SOURCE_KEYS=\["program","programme","itineraryDays","dailyProgram","travelProgram","itinerary","activities","agenda","timeline"\]/);
    assert.match(js,/function programSource\(customer\)/);
    assert.match(js,/function programEditValues\(customer\)/);
    assert.match(js,/function generatedProgramDays\(customer\)/);
    assert.match(js,/function groupFlatProgramItems\(items,dates\)/);
    assert.match(js,/source\.value\.length&&source\.value\.every\(isFlatProgramItem\)/);
    assert.match(js,/function programTabMarkup\(customer\)/);
    assert.match(js,/function programEditFormMarkup\(customer\)/);
    assert.match(js,/data-program-edit-action="edit">Programm bearbeiten/);
    assert.match(js,/data-program-edit-action="add-item"/);
    assert.match(js,/data-program-edit-action="add-day"/);
    assert.match(js,/data-program-edit-action="delete-day"/);
    assert.match(js,/data-program-edit-action="move-up"/);
    assert.match(js,/data-program-edit-action="move-down"/);
    assert.match(js,/programInput\(prefix,"startTime","Uhrzeit von",item\.startTime\|\|item\.time,\{type:"time"/);
    assert.match(js,/programInput\(prefix,"endTime","Uhrzeit bis",item\.endTime,\{type:"time",error:endTimeError/);
    assert.match(js,/programCheckbox\(prefix,"allDay","Ganztagig"/);
    assert.match(js,/Ganztagig/);
    assert.match(js,/programInput\(prefix,"location","Standort \/ Adresse",item\.location/);
    assert.match(js,/programInput\(prefix,"eventUrl","Veranstaltungslink",item\.eventUrl,\{type:"url"/);
    assert.doesNotMatch(js,/programInput\(prefix,"duration","Dauer"/);
    assert.match(css,/\.v2-program-overview,\.v2-program-days,\.v2-program-editor,\.v2-program-edit-items\{display:grid;gap:16px\}/);
    assert.match(css,/\.v2-program-item\{display:grid;grid-template-columns:minmax\(76px,96px\) minmax\(0,1fr\)/);
    assert.match(css,/\.v2-icon-button\{width:44px;height:44px/);
    assert.match(css,/\.v2-program-links/);
  });

  it("validates itinerary times, maps links and safe event URLs",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(js,/function safeWebUrl\(value\)/);
    assert.match(js,/!\["http:","https:"\]\.includes\(url\.protocol\)/);
    assert.match(js,/raw\)\?raw:`https:\/\/\$\{raw\}`/);
    assert.match(js,/function mapSearchUrl\(location\)/);
    assert.match(js,/google\.com\/maps\/search\/\?api=1&query=\$\{encodeURIComponent\(query\)\}/);
    assert.match(js,/function programTimeLabel\(item\)/);
    assert.match(js,/item\.time&&item\.endTime/);
    assert.match(js,/item\.endTime&&!item\.startTime/);
    assert.match(js,/Bitte zuerst eine Startzeit eingeben\./);
    assert.match(js,/item\.startTime&&item\.endTime&&item\.endTime<item\.startTime/);
    assert.match(js,/Die Endzeit darf nicht vor der Startzeit liegen\./);
    assert.match(js,/cleanValue\(item\.eventUrl\)&&!safeWebUrl\(item\.eventUrl\)/);
    assert.match(js,/Bitte gib eine gueltige Webadresse ein\./);
    assert.match(js,/target="_blank" rel="noopener noreferrer">In Maps oeffnen/);
    assert.match(js,/target="_blank" rel="noopener noreferrer">Veranstaltung oeffnen/);
    assert.match(js,/item\.duration&&!item\.endTime/);
    assert.match(js,/Legacy-Dauer/);
    assert.match(css,/\.v2-program-item\.no-time\{grid-template-columns:1fr\}/);
    assert.match(css,/\.v2-program-links \.v2-button\{min-height:44px/);
  });

  it("adds intelligent itinerary fields without changing the program storage facade",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(js,/const PROGRAM_PRIORITIES=\["","Highlight","Empfehlenswert","Optional","Schlechtwetteralternative"\]/);
    assert.match(js,/function mapNavigationUrl\(location\)/);
    assert.match(js,/google\.com\/maps\/dir\/\?api=1&destination=\$\{encodeURIComponent\(query\)\}/);
    assert.match(js,/function emailLink\(value\)/);
    assert.match(js,/return `mailto:\$\{encodeURIComponent\(email\)\}`/);
    assert.match(js,/function phoneLink\(value\)/);
    assert.match(js,/return `tel:\$\{compact\}`/);
    assert.match(js,/function locationSummary\(item\)/);
    assert.match(js,/function programPriorityBadge\(value\)/);
    assert.match(js,/function programPriceLabel\(item\)/);
    assert.match(js,/venueName:firstValue\(item\.venueName,item\.venue,item\.locationName,item\.placeName\)/);
    assert.match(js,/contactName:firstValue\(item\.contactName,item\.contact,item\.contactPerson,item\.ansprechpartner\)/);
    assert.match(js,/weatherPlaceholder:firstValue\(item\.weatherPlaceholder,item\.weather,item\.weatherHint\)/);
    assert.match(js,/internalNotes:firstValue\(item\.internalNotes,item\.adminNotes,item\.privateNotes,item\.internalNote\)/);
    assert.match(js,/programInput\(prefix,"contactPhone","Telefon",item\.contactPhone,\{type:"tel"/);
    assert.match(js,/programInput\(prefix,"contactEmail","E-Mail",item\.contactEmail,\{type:"email",error:contactEmailError/);
    assert.match(js,/programSelect\(prefix,"priority","Prioritaet",item\.priority,PROGRAM_PRIORITIES/);
    assert.match(js,/programInput\(prefix,"price","Preis",item\.price/);
    assert.match(js,/programInput\(prefix,"websiteUrl","Offizielle Website",item\.websiteUrl,\{type:"url",error:websiteUrlError/);
    assert.match(js,/programInput\(prefix,"ticketNumber","Ticketnummer",item\.ticketNumber/);
    assert.match(js,/programInput\(prefix,"voucherNumber","Vouchernummer",item\.voucherNumber/);
    assert.match(js,/programTextarea\(prefix,"internalNotes","Interne Notizen \(nur Admin\)",item\.internalNotes/);
    assert.match(js,/data-program-edit-action="duplicate-item"/);
    assert.match(js,/function duplicateProgramItem\(dayIndex,itemIndex\)/);
    assert.match(js,/function moveProgramItemToDay\(dayIndex,itemIndex,targetDayIndex\)/);
    assert.match(js,/name="moveToDay" data-program-edit-action="move-to-day"/);
    assert.match(css,/\.v2-program-priority/);
    assert.match(css,/\.v2-program-facts/);
    assert.match(css,/\.v2-admin-note/);
    assert.match(css,/\.v2-program-image/);
    assert.doesNotMatch(js,/setDoc\(|updateDoc\(|deleteDoc\(|firestoreModule/);
    assert.match(js,/window\.ACTFirebaseDatabase\.saveDraftCustomer\(fullCustomer\)/);
  });

  it("adds document metadata management without changing redaction",()=>{
    const html=readProjectFile("customer-portal/admin-v2.html");
    const js=readProjectFile("customer-portal/admin-v2.js");
    const css=readProjectFile("customer-portal/admin-v2.css");
    const redact=readProjectFile("customer-portal/redact-allowlist.js");
    assert.match(html,/id="documentsRoot"/);
    assert.match(js,/documentEditMode:false/);
    assert.match(js,/let documentSavePromise=null/);
    assert.match(js,/const DOCUMENT_CATEGORIES=\["Reiseunterlagen","Transport","Unterkunft","Aktivitaet","Restaurant","Versicherung","Identitaetsdokument","Rechnung","Vertrag","Flug","Hotel","Transfer","Mietwagen","Ticket","Voucher","Reisepass","Visum","Sonstiges"\]/);
    assert.match(js,/const DOCUMENT_TYPES=\["PDF","Bild","Ticket","Voucher","Buchungsbestaetigung","Boarding Pass","Fahrkarte","Hotel","Flug","Transfer","Restaurant","Rechnung","Vertrag","Versicherung","Reisepass","Visum","QR-Code","Link","Sonstiges","Text","Dokument"\]/);
    assert.match(js,/const DOCUMENT_ASSIGNMENTS=\["Reise","Reisetag","Programmpunkt","Buchung","Allgemeines Kundendokument","Nicht zugeordnet"\]/);
    assert.match(js,/function normalizeDocumentItem\(item,index=0\)/);
    assert.match(js,/categoryCandidate=firstValue\(doc\.category,doc\.documentCategory,DOCUMENT_CATEGORIES\.includes\(doc\.type\)\?doc\.type:"","Sonstiges"\)/);
    assert.match(js,/category:categoryCandidate\|\|"Sonstiges"/);
    assert.match(js,/programItemId:firstValue\(doc\.programItemId,doc\.programId,doc\.activityId,doc\.itemId\)/);
    assert.match(js,/bookingId:firstValue\(doc\.bookingId,doc\.booking,doc\.reservationId\)/);
    assert.match(js,/expiryDate:dateInputValue\(firstValue\(doc\.expiryDate,doc\.expiresAt,doc\.validUntil,doc\.ablaufdatum\)\)/);
    assert.match(js,/issuer:firstValue\(doc\.issuer,doc\.provider,doc\.vendor,doc\.aussteller\)/);
    assert.match(js,/referenceNumber:firstValue\(doc\.referenceNumber,doc\.reference,doc\.confirmationNumber,doc\.ref\)/);
    assert.match(js,/tags:normalizeTags\(doc\.tags\)/);
    assert.match(js,/function documentStatus\(doc\)/);
    assert.match(js,/return "Abgelaufen"/);
    assert.match(js,/return "Laeuft bald ab"/);
    assert.match(js,/function documentPreview\(doc\)/);
    assert.match(js,/class="v2-document-thumb"/);
    assert.match(js,/function documentMatchesProgramItem\(doc,item\)/);
    assert.match(js,/class="v2-program-attachments"/);
    assert.match(js,/function filteredDocumentRecords\(\)/);
    assert.match(js,/function compareDocuments\(a,b,sort=state\.documentSort\)/);
    assert.match(js,/data-document-edit-action="edit">Dokumente bearbeiten/);
    assert.match(js,/documentSelect\(prefix,"category","Kategorie",doc\.category,DOCUMENT_CATEGORIES/);
    assert.match(js,/documentSelect\(prefix,"documentType","Dokumenttyp",doc\.documentType,DOCUMENT_TYPES/);
    assert.match(js,/documentVisibilityToggle\(prefix,doc\.visibility\|\|"Kundenportal",index\)/);
    assert.match(js,/AN · Fuer Kunden sichtbar/);
    assert.match(js,/AUS · Nur intern/);
    assert.match(js,/documentSelect\(prefix,"assignmentType","Zuordnung",doc\.assignmentType\|\|"Reise",DOCUMENT_ASSIGNMENTS/);
    assert.match(js,/documentInput\(prefix,"programItemId","Programmpunkt",doc\.programItemId/);
    assert.match(js,/documentInput\(prefix,"bookingId","Buchung",doc\.bookingId/);
    assert.match(js,/documentInput\(prefix,"tripId","Reise",doc\.tripId/);
    assert.match(js,/documentInput\(prefix,"issueDate","Ausstellungsdatum",doc\.issueDate,\{type:"date"/);
    assert.match(js,/documentInput\(prefix,"expiryDate","Ablaufdatum",doc\.expiryDate,\{type:"date"/);
    assert.match(js,/documentSelect\(prefix,"status","Status",doc\.status\|\|"Aktiv",\["Aktiv","Archiviert"\]/);
    assert.match(js,/documentTextarea\(prefix,"description","Beschreibung",doc\.description/);
    assert.match(js,/documentTextarea\(prefix,"internalNotes","Interne Notizen \(nur Admin\)",doc\.internalNotes/);
    assert.match(js,/function deleteDocumentEditItem\(index\)/);
    assert.match(js,/Dieses Dokument aus dem Kundenentwurf entfernen/);
    assert.match(js,/data-document-edit-action="delete"/);
    assert.match(js,/Datei ersetzen/);
    assert.match(js,/disabled title="Die bestehende Upload-Logik bietet noch keine sichere Datei-Ersetzung\."/);
    assert.match(js,/if\(cleanValue\(item\.url\)&&!safeDocumentUrl\(item\.url\)\)/);
    assert.match(js,/function preserveDocumentFileFields\(item,previous\)/);
    assert.match(js,/function restoreMissingDocumentUrls\(draft,previousDocuments=\[\]\)/);
    assert.match(js,/Sichtbar im Kundenportal erfordert einen gueltigen Oeffnen-Link/);
    assert.match(js,/documentInput\(prefix,"url","Oeffnen-Link",doc\.url,\{type:"text"/);
    assert.match(js,/documentInput\(prefix,"downloadUrl","Download-Link",doc\.downloadUrl,\{type:"text"/);
    assert.match(js,/window\.ACTFirebaseDatabase\.saveDraftCustomer\(fullCustomer\)/);
    assert.match(css,/\.v2-document-card/);
    assert.match(css,/\.v2-document-actions \.v2-button\{min-height:44px/);
    assert.match(redact,/const DOCUMENT_PUBLIC_FIELDS=new Set\(\[/);
    const publicDocumentFields=redact.match(/const DOCUMENT_PUBLIC_FIELDS=new Set\(\[([\s\S]*?)\]\);/)[1];
    assert.doesNotMatch(publicDocumentFields,/internalNotes/);
    assert.doesNotMatch(js,/setDoc\(|updateDoc\(|deleteDoc\(|firestoreModule/);
  });

  it("integrates Admin V2 uploads through the existing Firebase Storage adapter",()=>{
    const html=readProjectFile("customer-portal/admin-v2.html");
    const js=readProjectFile("customer-portal/admin-v2.js");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(html,/admin-v2\.css\?v=26/);
    assert.match(html,/portal-share-library\.js\?v=2/);
    assert.match(html,/publish-workflow\.js\?v=4/);
    assert.match(html,/firebase-storage\.js\?v=4/);
    assert.match(html,/admin-v2\.js\?v=26"><\/script>/);
    assert.match(js,/const MAX_UPLOAD_BYTES=24\*1024\*1024/);
    assert.match(js,/window\.ACTFirebaseStorage\.uploadCustomerDocument\(/);
    assert.match(js,/resolveDocumentDownloadUrl/);
    assert.match(js,/function documentUploadReady\(\)/);
    assert.match(js,/typeof window\.ACTFirebaseStorage\?\.uploadCustomerDocument==="function"/);
    assert.match(js,/Der Datei-Upload konnte nicht initialisiert werden\. Firebase Storage ist derzeit nicht verfuegbar\./);
    assert.match(js,/aria-disabled="\$\{uploadReady\?"false":"true"\}"/);
    assert.match(js,/if\(!documentUploadReady\(\)\)\{/);
    assert.match(js,/window\.ACTFirebaseDatabase\.saveDraftCustomer\(fullCustomer\)/);
    assert.match(js,/function persistUploadedDocument\(customer,documentItem\)/);
    assert.match(js,/function retryDocumentUpload\(id\)/);
    assert.match(js,/data-upload-retry/);
    assert.match(js,/Dateityp nicht vorgesehen/);
    assert.match(js,/Die Datei ist zu gross\. Maximal erlaubt sind 24 MB\./);
    assert.match(css,/\.v2-upload-panel/);
    assert.match(css,/\.v2-upload-row progress/);
    assert.match(css,/\.v2-upload-actions \.v2-button\{min-height:48px/);
    assert.match(css,/\.v2-upload-actions \.v2-button\.disabled/);
    assert.match(css,/\.v2-upload-warning/);
    assert.match(css,/\.v2-file-input/);
    assert.doesNotMatch(js,/uploadBytesResumable\(|getDownloadURL\(|ref\(ready\.storage/);
    assert.doesNotMatch(js,/setDoc\(|updateDoc\(|deleteDoc\(|firestoreModule/);
  });

  it("analyzes document links, quality, duplicates, missing documents and expiry locally",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(js,/documentQuality:""/);
    assert.match(js,/const DOCUMENT_QUALITY_FILTERS=\["","Vollstaendig","Hinweise","Kritisch","Nicht zugeordnet","Doppelt","Abgelaufen","Laeuft bald ab"\]/);
    assert.match(js,/const DOCUMENT_REQUIRED_BY_PROGRAM_CATEGORY=\{/);
    assert.match(js,/flug:\["Ticket"\]/);
    assert.match(js,/hotel:\["Voucher"\]/);
    assert.match(js,/mietwagen:\["Mietwagen"\]/);
    assert.match(js,/function flattenProgramItems\(customer\)/);
    assert.match(js,/function inferDocumentProgramMatch\(doc,programItems\)/);
    assert.match(js,/if\(\["versicherung","rechnung"\]\.includes\(key\)\)return \{assignmentType:"Reise",reason:"Reisedokument"\}/);
    assert.match(js,/if\(matches\.length===1\)return \{assignmentType:"Programmpunkt",programItemId:matches\[0\]\.stableId/);
    assert.match(js,/function duplicateDocumentKeys\(docs\)/);
    assert.match(js,/function documentQuality\(doc,\{programItems=\[\],duplicateKeys=null\}=\{\}\)/);
    assert.match(js,/issues\.push\("keinem Programmpunkt zugeordnet"\)/);
    assert.match(js,/issues\.push\("doppeltes Dokument"\)/);
    assert.match(js,/function documentAnalysis\(customer\)/);
    assert.match(js,/function missingDocumentsForProgram\(customer,rows\)/);
    assert.match(js,/message:`\$\{category\} fehlt fuer \$\{item\.title\|\|"Programmpunkt"\}`/);
    assert.match(js,/function documentQualitySummary\(customer\)/);
    assert.match(js,/function allDocumentQualitySummary\(\)/);
    assert.match(js,/const docStats=allDocumentQualitySummary\(\)/);
    assert.match(js,/Dokumente · \$\{docStats\.complete\} vollstaendig · \$\{docStats\.issues\} Hinweise · \$\{docStats\.critical\} kritisch/);
    assert.match(js,/if\(state\.documentQuality==="Nicht zugeordnet"/);
    assert.match(js,/if\(state\.documentQuality==="Doppelt"/);
    assert.match(js,/if\(state\.documentQuality==="Abgelaufen"/);
    assert.match(js,/documentQualityFilter/);
    assert.match(js,/data-open-documents/);
    assert.match(js,/Vorschlag:/);
    assert.match(js,/data-document-edit-action="apply-suggestion"/);
    assert.match(js,/Dokumentenqualitaet/);
    assert.match(js,/Heute abgelaufen:/);
    assert.match(js,/In 7 Tagen:/);
    assert.match(js,/In 30 Tagen:/);
    assert.match(css,/\.v2-document-suggestion/);
    assert.match(css,/\.v2-document-issues/);
    assert.match(css,/\.v2-document-quality-grid/);
    assert.match(css,/\.v2-document-controls\{display:grid;grid-template-columns:2fr repeat\(6,minmax\(140px,1fr\)\)/);
    assert.doesNotMatch(js,/setDoc\(|updateDoc\(|deleteDoc\(|firestoreModule/);
  });

  it("makes document analysis actionable without bypassing secure portal or draft facades",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(js,/documentFocusIndex:null/);
    assert.match(js,/function documentIssueField\(issue\)/);
    assert.match(js,/function documentIssueListMarkup\(doc,quality,\{customer=null,index=0,edit=false\}=\{\}\)/);
    assert.match(js,/data-document-edit-action="edit-issue"/);
    assert.match(js,/data-document-field="\$\{escapeHtml\(field\)\}"/);
    assert.match(js,/function openDocumentEditor\(customerId,index=null,field=""\)/);
    assert.match(js,/target\.closest\("\.v2-document-edit-item"\)\?\.scrollIntoView/);
    assert.match(js,/data-document-edit-action="edit-one"/);
    assert.match(js,/Details bearbeiten/);
    assert.match(js,/function applyDocumentSuggestion\(index\)/);
    assert.match(js,/Vorschlag uebernommen\. Bitte speichern/);
    assert.match(js,/function documentCompleteness\(doc,quality=documentQuality\(doc\)\)/);
    assert.match(js,/class="v2-quality-meter"/);
    assert.match(js,/documentMetricButton\("Kundenportal sichtbar"/);
    assert.match(js,/documentMetricButton\("Nur intern"/);
    assert.match(js,/Noch kein sicherer Kunden-Link erzeugt/);
    assert.match(js,/const canPreview=Boolean\(link\.canOpen&&link\.url\)/);
    assert.match(js,/if\(!link\.canOpen\|\|!link\.url\)/);
    assert.doesNotMatch(js,/params\.set\("customer"/);
    assert.match(js,/ACTPortalShareLibrary\.buildShareUrl|lib\?\.buildShareUrl/);
    assert.match(js,/window\.ACTFirebaseDatabase\.saveDraftCustomer\(fullCustomer\)/);
    assert.doesNotMatch(js,/setDoc\(|updateDoc\(|deleteDoc\(|firestoreModule/);
    assert.doesNotMatch(js,/uploadBytesResumable\(|getDownloadURL\(|ref\(ready\.storage/);
    assert.match(css,/\.v2-quality-meter/);
    assert.match(css,/\.v2-link-button/);
  });

  it("integrates publication and secure portal links through existing facades only",()=>{
    const html=readProjectFile("customer-portal/admin-v2.html");
    const js=readProjectFile("customer-portal/admin-v2.js");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(html,/redact-allowlist\.js\?v=2/);
    assert.match(html,/redact-public-snapshot\.js\?v=2/);
    assert.match(html,/portal-share-library\.js\?v=2/);
    assert.match(html,/publish-workflow\.js\?v=4/);
    assert.match(js,/tab==="veroeffentlichung"\?publicationTabMarkup\(customer\):placeholderTabMarkup\(\)/);
    assert.match(js,/function publicationTabMarkup\(customer\)/);
    assert.match(js,/function publishCustomerV2\(\)/);
    assert.match(js,/workflow\?\.validateForPublish\?workflow\.validateForPublish\(customer\)/);
    assert.match(js,/db\.publishCustomer\(clone\(publishCandidate\),meta\)/);
    assert.match(js,/function createPortalShareV2\(\)/);
    assert.match(js,/db\.createPortalShare\(clone\(customer\)\)/);
    assert.match(js,/function revokePortalShareV2\(\)/);
    assert.match(js,/db\.revokePortalShare\(share\.shareId\)/);
    assert.match(js,/function buildShareLink\(shareId,rawToken\)/);
    assert.match(js,/function secureShareUrl\(url\)/);
    assert.match(js,/parsed\.searchParams\.get\("share"\)/);
    assert.match(js,/parsed\.searchParams\.get\("token"\)/);
    assert.match(js,/parsed\.searchParams\.get\("customer"\)/);
    assert.match(js,/sessionStorage\.getItem\(SHARE_TOKEN_KEY\)/);
    assert.match(js,/Portal-Vorschau oeffnen/);
    assert.match(js,/Kundenportal oeffnen/);
    assert.match(js,/Sicheren Link kopieren/);
    assert.match(js,/Sicheren Link erzeugen/);
    assert.match(js,/Share-Link widerrufen/);
    assert.match(js,/publicationWarnings\(customer\)/);
    assert.match(js,/sichtbare Dokumente haben keinen Oeffnen-Link/);
    assert.match(js,/Aenderungen seit letzter Veroeffentlichung/);
    assert.match(css,/\.v2-publication-overview/);
    assert.match(css,/\.v2-share-link/);
    assert.match(css,/\.v2-warning-list/);
    assert.doesNotMatch(js,/setDoc\(|updateDoc\(|deleteDoc\(|firestoreModule/);
    assert.doesNotMatch(js,/uploadBytesResumable\(|getDownloadURL\(|ref\(ready\.storage/);
  });

  it("saves program edits through the existing draft facade without direct Firestore",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/function validateProgramEdit\(draft\)/);
    assert.match(js,/errors\[`program-\$\{dayIndex\}-\$\{itemIndex\}-title`\]="Bitte einen Titel eingeben\."/);
    assert.match(js,/function mergeProgramEdit\(customer,values\)/);
    assert.match(js,/const fullCustomer=mergeProgramEdit\(customer,validation\.values\)/);
    assert.match(js,/window\.ACTFirebaseDatabase\.saveDraftCustomer\(fullCustomer\)/);
    assert.match(js,/Programm erfolgreich gespeichert\./);
    assert.match(js,/if\(values\.sourceScope==="root"\|\|key in next\)next\[key\]=days/);
    assert.match(js,/updateProgramObjects\(next,values,days\)/);
    assert.match(js,/function sortProgramItems\(items\)/);
    assert.match(js,/state\.programEditMode&&programEditFingerprint/);
    assert.match(js,/hasDirtyCustomerEdit\(\)\|\|hasDirtyTripEdit\(\)\|\|hasDirtyProgramEdit\(\)/);
    assert.doesNotMatch(js,/setDoc\(|updateDoc\(|deleteDoc\(|firestoreModule/);
  });

  it("normalizes dates, statuses and partial legacy trip data without mutating storage",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/function dateValue\(value\)\{/);
    assert.match(js,/typeof value\.toDate==="function"/);
    assert.match(js,/Number\.isFinite\(value\.seconds\)/);
    assert.match(js,/raw\.match\(\/\^\(\\d\{1,2\}\)\\\.\(\\d\{1,2\}\)\\\.\(\\d\{4\}\)\$\/\)/);
    assert.match(js,/function formatTripPeriod\(startValue,endValue,fallback=""\)/);
    assert.match(js,/function nightCount\(startValue,endValue\)/);
    assert.match(js,/function statusLabel\(value\)/);
    assert.match(js,/draft","entwurf/);
    assert.match(js,/published","veroeffentlicht"/);
    assert.match(js,/cancelled","canceled","storniert"/);
    assert.match(js,/cleanValue\(value\)/);
    assert.match(js,/undefined|null/);
    assert.doesNotMatch(js,/next\.travel=|next\.trip=|customer\.travel=/);
  });

  it("handles invalid customer ids and keeps the classic edit fallback",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/const CUSTOMER_NOT_FOUND_ERROR="Der ausgewaehlte Kunde konnte nicht gefunden werden\."/);
    assert.match(js,/CUSTOMER_NOT_FOUND_ERROR/);
    assert.match(js,/function classicEditorUrl\(id\)/);
    assert.match(js,/admin\.html\?editCustomer=\$\{encodeURIComponent\(id\|\|""\)\}#master-data/);
    assert.match(js,/Im klassischen Admin bearbeiten/);
    assert.match(js,/Zur Kundenuebersicht/);
  });

  it("uses the existing draft save facade without direct Firestore in edit flows",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/window\.ACTFirebaseDatabase\.saveDraftCustomer\(fullCustomer\)/);
    assert.match(js,/function mergeCustomerEdit\(customer,values\)/);
    assert.match(js,/const next=clone\(customer\)/);
    assert.match(js,/updateLocalCustomer\(fullCustomer\)/);
    assert.doesNotMatch(js,/setDoc\(|updateDoc\(|deleteDoc\(|firestoreModule/);
  });

  it("opens the new-customer wizard in admin v2 without redirecting to classic admin",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    const html=readProjectFile("customer-portal/admin-v2.html");
    assert.match(html,/admin-v2\.css\?v=26/);
    assert.match(html,/admin-v2\.js\?v=26/);
    assert.match(html,/data-new-customer>Neuen Kunden anlegen/);
    assert.match(html,/id="newCustomerWizard"/);
    assert.match(html,/data-wizard-action="cancel">Abbrechen/);
    assert.match(html,/data-wizard-action="back" id="wizardBackButton">Zurueck/);
    assert.match(html,/data-wizard-action="next" id="wizardNextButton">Weiter/);
    assert.match(js,/function openNewCustomer\(\)/);
    assert.match(js,/state\.wizardOpen=true/);
    assert.match(js,/renderNewCustomerWizard\(\)/);
    assert.match(js,/byId\("newCustomerWizard"\)/);
    assert.match(js,/const WIZARD_STEPS=\[/);
    assert.match(js,/function handleWizardAction\(action\)/);
    assert.match(js,/function saveWizardDraftCustomer\(/);
    assert.match(js,/window\.ACTFirebaseDatabase\.saveDraftCustomer\(fullCustomer\)/);
    assert.match(js,/function wizardPublish\(\)/);
    assert.match(js,/publishCustomerV2\(\)/);
    assert.match(js,/function wizardCreateShare\(\)/);
    assert.match(js,/createPortalShareV2\(\)/);
    assert.match(js,/data-wizard-action="save-draft"/);
    assert.match(js,/data-wizard-action="publish"/);
    assert.match(js,/data-wizard-action="create-share"/);
    assert.match(js,/<h3>1\. Kundendaten<\/h3>/);
    assert.match(js,/<h3>2\. Reise<\/h3>/);
    assert.match(js,/<h3>3\. Programm<\/h3>/);
    assert.match(js,/<h3>4\. Dokumente<\/h3>/);
    assert.match(js,/<h3>5\. Pruefung<\/h3>/);
    assert.match(js,/<h3>6\. Abschluss<\/h3>/);
    assert.match(js,/<li>Uebersprungen<\/li>/);
    assert.match(js,/function wizardMissingItems\(draft\)/);
    assert.match(js,/missing\.push\("Kundenname"\)/);
    assert.match(js,/missing\.push\("Telefon oder E-Mail"\)/);
    assert.match(js,/missing\.push\("Reisetitel"\)/);
    assert.match(js,/event\.target\.closest\("\[data-wizard-action\]"\)/);
    assert.match(js,/handleWizardAction\(wizardAction\.dataset\.wizardAction\)/);
    assert.match(js,/function handleWizardInput\(event\)/);
    assert.match(js,/function syncWizardFieldsFromDom\(\)/);
    assert.doesNotMatch(js,/window\.location\.href="admin\.html\?newCustomer=1#master-data"/);
    assert.doesNotMatch(js,/function openNewCustomer\(\)\{[^}]*location\.href/);
    assert.doesNotMatch(js,/href="admin\.html\?newCustomer=1#master-data"/);
    assert.match(js,/Klassischen Admin in neuem Tab oeffnen/);
    assert.match(js,/href="admin\.html"/);
  });

  it("supports controlled customer edit mode, cancel, dirty warning and validation",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/customerEditMode:false/);
    assert.match(js,/customerEditDraft:null/);
    assert.match(js,/function startCustomerEdit\(customer\)/);
    assert.match(js,/function cancelCustomerEdit\(\)/);
    assert.match(js,/function hasDirtyCustomerEdit\(\)/);
    assert.match(js,/function confirmDiscardCustomerEdit\(\)/);
    assert.match(js,/Ungespeicherte Aenderungen verwerfen\?/);
    assert.match(js,/function validateCustomerEdit\(draft\)/);
    assert.match(js,/errors\.customerName="Bitte einen Kundennamen eingeben\."/);
    assert.match(js,/Bitte eine gueltige E-Mail-Adresse eingeben\./);
    assert.match(js,/aria-invalid="\$\{error\?"true":"false"\}"/);
    assert.match(js,/data-customer-edit-action="save"/);
    assert.match(js,/data-customer-edit-action="cancel"/);
  });

  it("preserves non-customer data by merging edits into the full customer object",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    assert.match(js,/const fullCustomer=mergeCustomerEdit\(customer,validation\.values\)/);
    assert.match(js,/next\.customerName=values\.customerName/);
    assert.match(js,/next\.contact=\{/);
    assert.match(js,/next\.updatedAt=new Date\(\)\.toLocaleDateString\("de-DE"\)/);
    assert.doesNotMatch(js,/next\.program=\[\]|next\.documents=\[\]|next\.publishedSnapshot=null|next\.publishMeta=\{\}/);
  });

  it("keeps mobile customer edit form usable at narrow widths",()=>{
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(css,/\.v2-edit-grid\{display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
    assert.match(css,/input,select,textarea\{font-size:16px;line-height:1\.3\}/);
    assert.match(css,/\.v2-edit-field input,\.v2-edit-field textarea,\.v2-edit-field select\{[^}]*font-size:16px/);
    assert.match(css,/\.v2-edit-actions\{position:sticky/);
    assert.match(css,/@media \(max-width:820px\),\(max-width:920px\) and \(max-height:520px\)/);
    assert.match(css,/\.v2-edit-grid\{grid-template-columns:1fr\}/);
    assert.match(css,/\.v2-edit-actions \.v2-button\{width:100%\}/);
    assert.match(css,/min-height:48px/);
  });

  it("protects mobile content from bottom navigation and safe-area overlap",()=>{
    const html=readProjectFile("customer-portal/admin-v2.html");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(html,/width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover, interactive-widget=resizes-content/);
    assert.match(css,/html\{width:100%;max-width:100%;overflow-x:hidden;-webkit-text-size-adjust:100%;text-size-adjust:100%;touch-action:pan-y\}/);
    assert.match(css,/body\{width:100%;max-width:100%;margin:0;overflow-x:hidden;overscroll-behavior-x:none;touch-action:pan-y/);
    assert.match(css,/main\{width:100%;min-width:0;max-width:100%;overflow-x:hidden\}/);
    assert.match(css,/--mobile-safe-top:env\(safe-area-inset-top,0px\)/);
    assert.match(css,/\.v2-shell\{width:100%;max-width:100%;min-height:100dvh;display:grid;grid-template-columns:280px minmax\(0,1fr\)\}/);
    assert.match(css,/\.v2-main\{min-width:0;max-width:100%;padding:calc\(26px \+ var\(--mobile-safe-top\)\)/);
    assert.match(css,/\.v2-topbar>\*,\.v2-section-toolbar>\*\{min-width:0;max-width:100%\}/);
    assert.match(css,/\.v2-search\{min-height:48px;min-width:0;max-width:100%/);
    assert.match(css,/\.v2-profile\{min-width:0;max-width:100%;min-height:54px;display:grid;grid-template-columns:minmax\(0,1fr\) auto;.*overflow:hidden/);
    assert.match(css,/--mobile-nav-height:0px/);
    assert.match(css,/--mobile-safe-bottom:env\(safe-area-inset-bottom,0px\)/);
    assert.match(css,/:root\{--mobile-nav-height:136px;--mobile-nav-gap:20px\}/);
    assert.match(css,/html,body\{width:100%;max-width:100%;overflow-x:hidden\}/);
    assert.match(css,/\.v2-brand,\.v2-create,\.v2-classic-link\{display:none\}/);
    assert.match(css,/\.v2-nav\{display:grid;grid-template-columns:repeat\(3,minmax\(0,1fr\)\);gap:6px;overflow:visible\}/);
    assert.match(css,/\.v2-nav-item\{white-space:normal;min-height:54px/);
    assert.match(css,/\.v2-nav-icon\{width:24px;height:24px/);
    assert.match(css,/bottom:calc\(12px \+ var\(--mobile-safe-bottom\)\)/);
    assert.match(css,/\.v2-main\{padding:calc\(18px \+ var\(--mobile-safe-top\)\) 12px calc\(var\(--mobile-nav-height\) \+ var\(--mobile-nav-gap\) \+ var\(--mobile-safe-bottom\) \+ 32px\)\}/);
    assert.match(css,/bottom:calc\(var\(--mobile-nav-height\) \+ var\(--mobile-nav-gap\) \+ var\(--mobile-safe-bottom\)\)/);
    assert.match(css,/@media \(max-width:820px\) and \(orientation:landscape\)/);
  });

  it("provides search, filter, sorting, empty and retry states",()=>{
    const js=readProjectFile("customer-portal/admin-v2.js");
    const html=readProjectFile("customer-portal/admin-v2.html");
    const css=readProjectFile("customer-portal/admin-v2.css");
    assert.match(js,/function filteredCustomers\(\)/);
    assert.match(js,/function compareCustomers\(a,b\)/);
    assert.match(js,/function resetFilters\(\)/);
    assert.match(html,/id="customerEmpty"/);
    assert.match(js,/retryInlineButton/);
    assert.match(html,/id="customerSearchInput"/);
    assert.match(html,/id="toggleFiltersButton" aria-expanded="false" aria-controls="advancedFilters"/);
    assert.match(html,/id="advancedFilters" hidden/);
    assert.match(html,/id="activeFilterSummary"/);
    assert.match(js,/filtersExpanded:false/);
    assert.match(js,/function activeAdvancedFilters\(\)/);
    assert.match(js,/function renderFilterDisclosure\(\)/);
    assert.match(js,/toggle\.textContent=state\.filtersExpanded\?"Filter ausblenden":active\.length\?`Filter · \$\{active\.length\} aktiv`:"Filter anzeigen"/);
    assert.match(js,/reset\.disabled=!active\.length/);
    assert.match(js,/function toggleAdvancedFilters\(\)/);
    assert.match(css,/\.v2-filterbar\{grid-template-columns:1fr/);
    assert.match(css,/\.v2-filter-advanced\[hidden\]\{display:none!important\}/);
    assert.match(css,/\.v2-filter-advanced\{display:grid;grid-template-columns:repeat\(4,minmax\(128px,1fr\)\) auto/);
    assert.match(css,/\.v2-hero,\.v2-filterbar,\.v2-filter-advanced/);
  });

  it("classic admin accepts v2 handoff parameters without replacing existing logic",()=>{
    const adminJs=readProjectFile("customer-portal/admin.js");
    assert.match(adminJs,/function initialAdminAction\(\)/);
    assert.match(adminJs,/editCustomer:params\.get\("editCustomer"\)/);
    assert.match(adminJs,/newCustomer:params\.get\("newCustomer"\)==="1"/);
    assert.match(adminJs,/switchActiveCustomer\(action\.editCustomer,"edit"\)/);
    assert.match(adminJs,/newCustomer\(\)/);
  });
});
