window.CustomerPortalData={
  defaultCustomerId:"demo-a7k92m",
  customers:{
    "demo-a7k92m":{
      version:"1.0",
      updatedAt:"05.07.2026",
      publicationState:"Veröffentlicht",
      customerName:"Familie Müller",
      tripName:"Tirol Premium Weekend",
      travelPeriod:"22.-25. Juli 2027",
      startDate:"2027-07-22T10:00:00+02:00",
      region:"Tirol / Innsbruck / Seefeld",
      latitude:"47.3302",
      longitude:"11.1879",
      weatherLocationName:"Seefeld in Tirol",
      concierge:"Alpine Concierge Tirol",
      status:"Programm veröffentlicht",
      whatsapp:"+4367761410679",
      progressSteps:[
        "Anfrage eingegangen",
        "Angebot erstellt",
        "Angebot bestätigt",
        "Zahlung eingegangen",
        "Programm veröffentlicht",
        "Reise läuft",
        "Reise abgeschlossen"
      ],
      program:[
        {
          id:"arrival-checkin",
          date:"22. Juli 2027",
          dateValue:"2027-07-22",
          startTime:"15:00",
          endTime:"15:45",
          duration:"ca. 45 Minuten",
          title:"Anreise und privater Check-in",
          shortDescription:"Persönliche Begrüßung im Hotel und kurzer Programmüberblick.",
          description:"Persönliche Begrüßung im Hotel, kurzer Programmüberblick und Abstimmung letzter Wünsche.",
          meetingPoint:"Hotel Seefeld Lodge, Lobby",
          address:"Möserer Straße 18, 6100 Seefeld in Tirol",
          outfit:"Reisekleidung",
          notes:"Zimmer und Willkommensmappe sind vorbereitet.",
          contactPerson:"Alpine Concierge Tirol",
          phone:"+43 677 61410679",
          navigationUrl:"https://www.google.com/maps/search/?api=1&query=Hotel%20Seefeld%20Lodge%2C%20Seefeld%20in%20Tirol",
          status:"Bestätigt",
          category:"Hotel",
          colorClass:"type-hotel",
          images:[],
          documents:["Voucher"],
          calendarEnabled:true
        },
        {
          id:"innsbruck-city-genuss",
          date:"23. Juli 2027",
          dateValue:"2027-07-23",
          startTime:"09:30",
          endTime:"13:30",
          duration:"ca. 4 Stunden",
          title:"Innsbruck Private City & Genuss",
          shortDescription:"Privater Stadttag mit Führung, Nordkette-Blick und Genussmoment.",
          description:"Entspannter Stadttag mit privater Führung, Nordkette-Blick und kuratierter Kaffeepause.",
          meetingPoint:"Goldenes Dachl, Innsbruck",
          address:"Herzog-Friedrich-Straße 15, 6020 Innsbruck",
          outfit:"Bequeme Schuhe, leichte Jacke",
          notes:"Kinderfreundliches Tempo eingeplant.",
          contactPerson:"Guide Maria",
          phone:"+43 677 61410679",
          navigationUrl:"https://www.google.com/maps/search/?api=1&query=Goldenes%20Dachl%2C%20Innsbruck",
          status:"Bestätigt",
          category:"Aktivität",
          colorClass:"type-activity",
          images:[],
          documents:["Reiseunterlagen"],
          calendarEnabled:true
        },
        {
          id:"seefeld-picknick",
          date:"24. Juli 2027",
          dateValue:"2027-07-24",
          startTime:"10:00",
          endTime:"13:00",
          duration:"ca. 3 Stunden",
          title:"Seefeld Naturmoment mit Picknick",
          shortDescription:"Leichte Wanderung mit alpinem Picknick und optionaler Rückfahrt.",
          description:"Leichte Wanderung mit alpinem Picknick und optionaler Kutschenrückfahrt.",
          meetingPoint:"Seekirchl Seefeld",
          address:"Möserer Straße, 6100 Seefeld in Tirol",
          outfit:"Outdoor-Schuhe, Sonnenschutz",
          notes:"Schlechtwetteralternative: Spa-Zeit und Kaiserschmarrn-Tasting.",
          contactPerson:"Concierge Team",
          phone:"+43 677 61410679",
          navigationUrl:"https://www.google.com/maps/search/?api=1&query=Seekirchl%20Seefeld",
          status:"In Planung",
          category:"Freizeit",
          colorClass:"type-leisure",
          images:[],
          documents:["Voucher"],
          calendarEnabled:true
        },
        {
          id:"checkout-farewell",
          date:"25. Juli 2027",
          dateValue:"2027-07-25",
          startTime:"11:00",
          endTime:"11:20",
          duration:"ca. 20 Minuten",
          title:"Check-out und Abschied",
          shortDescription:"Flexible Abreise mit Gepäckservice und persönlicher Verabschiedung.",
          description:"Flexible Abreise mit Gepäckservice und persönlicher Verabschiedung.",
          meetingPoint:"Hotelrezeption",
          address:"Möserer Straße 18, 6100 Seefeld in Tirol",
          outfit:"Reisekleidung",
          notes:"Late Check-out ist angefragt.",
          contactPerson:"Alpine Concierge Tirol",
          phone:"+43 677 61410679",
          navigationUrl:"https://www.google.com/maps/search/?api=1&query=Hotel%20Seefeld%20Lodge%2C%20Seefeld%20in%20Tirol",
          status:"Angefragt",
          category:"Concierge",
          colorClass:"type-concierge",
          images:[],
          documents:["Reiseunterlagen"],
          calendarEnabled:true
        }
      ],
      hotel:{
        name:"Hotel Seefeld Lodge",
        address:"Möserer Straße 18, 6100 Seefeld in Tirol",
        checkIn:"22. Juli 2027, ab 15:00",
        checkOut:"25. Juli 2027, bis 11:00",
        contact:"+43 5212 00000",
        navigation:"Möserer Straße 18, Seefeld in Tirol",
        voucherStatus:"Voucher-Platzhalter vorbereitet"
      },
      documents:[
        {title:"Angebot",status:"Platzhalter"},
        {title:"Rechnung",status:"Platzhalter"},
        {title:"Voucher",status:"Platzhalter"},
        {title:"Tickets",status:"Platzhalter"},
        {title:"Reiseunterlagen",status:"Platzhalter"},
        {title:"Versicherungen",status:"Platzhalter"}
      ],
      contact:{
        company:"Alpine Concierge Tirol",
        phone:"+43 677 61410679",
        whatsapp:"+43 677 61410679",
        email:"alpineconcierge.tirol@gmail.com",
        emergency:"Persönlicher Notfallkontakt: +43 677 61410679",
        localEmergency:"Euro-Notruf 112, Rettung 144, Polizei 133, Feuerwehr 122"
      },
      weather:{
        summary:"",
        days:[]
      },
      history:[
        {date:"03.07.2026",text:"Restaurant geändert"},
        {date:"05.07.2026",text:"Transfer ergänzt"}
      ]
    }
  }
};
